/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic;

import com.toedter.calendar.JDateChooser;
import dao.*;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import pojo.*;

/**
 *
 * @author p-lao
 */
public class InvitationWD extends javax.swing.JFrame {
    
    private ArrayList <Evenement> evenements = new EvenementDAO().getAllAvailable();
    private ArrayList <Participant> participants = new ArrayList <Participant> ();
    
    private ArrayList <JTextField> jTextField = new ArrayList <JTextField> ();
    private ArrayList <JTextArea> jTextArea = new ArrayList <JTextArea> ();
    private ArrayList <JComboBox> jComboBox = new ArrayList <JComboBox> ();
    private ArrayList <JList> jList = new ArrayList <JList> ();
    private ArrayList <JDateChooser> jDateChooser = new ArrayList <JDateChooser> ();

    /**
     * Creates new form Invitation
     */
    public InvitationWD() {
        
        initComponents();
        
        jComboBoxEvenement();
        jListParticipant();
        
        listComponents();
        
        this.setLocationRelativeTo(null);
    }
    
    // Init Component
    
    public void listComponents() {
        
        jComboBox.add(jComboBoxEvenement);
        
        jList.add(jListParticipant);
    }
    
    public void jComboBoxEvenement() {
        
        this.jComboBoxEvenement.removeAllItems();
        
        // Add Data
        for ( Evenement evenement : this.evenements )
            this.jComboBoxEvenement.addItem( evenement.getIntitule() );
    }
    
    public void jListParticipant() {
        
        DefaultListModel listModel = new DefaultListModel();
        
        // Add Data
        for ( Participant participant : this.participants )
            listModel.addElement( participant.getNom() + " " + participant.getPrenom() + " - " + participant.getEmail() );
    
        this.jListParticipant.setSelectionMode( ListSelectionModel.MULTIPLE_INTERVAL_SELECTION );
        this.jListParticipant.setLayoutOrientation( JList.VERTICAL );
        this.jListParticipant.setVisibleRowCount( -1 );
        this.jListParticipant.setModel( listModel );
    }
    
    // Get Component content
    
    public Evenement getJComboBoxEvenement() {
        
        if ( this.jComboBoxEvenement.getSelectedIndex() != -1 )
            return this.evenements.get( this.jComboBoxEvenement.getSelectedIndex() );
        
        return null;
    }
    
    public ArrayList <Participant> getJListParticipant() {
        
        ArrayList <Participant> list = new ArrayList <Participant> ();
        
        for ( int indice : this.jListParticipant.getSelectedIndices() )
            list.add( this.participants.get( indice ) );
        
        return list;
    }
    
    // Check Component content
    
    public boolean checkJTextField() {
        
        for ( JTextField field : this.jTextField ) {
            if ( field.getText().length() == 0 )
                return false;
        }
            
        return true;
    }
    
    public boolean checkJTextArea() {
        
        for ( JTextArea field : this.jTextArea ) {
            if ( field.getText().length() == 0 )
                return false;
        }
        
        return true;
    }
    
    public boolean checkJComboBox() {
        
        for ( JComboBox field : this.jComboBox ) {
            if ( field.getSelectedIndex() == -1 )
                return false;
        }
        
        return true;
    }
    
    public boolean checkJList() {
        
        for ( JList field : this.jList ) {
            if ( field.getSelectedIndices().length == 0 )
                return false;
        }
        
        return true;
    }
    
    public boolean checkJDateChooser() {
        
        for ( JDateChooser field : this.jDateChooser ) {
            if ( field.getDate() == null )
                return false;
        }
        
        return true;
    }
    
    // Check Form
    
    public boolean checkForm() {
        
        return checkJTextField() && checkJTextArea() && checkJComboBox() && checkJList() && checkJDateChooser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAjouterInvite = new javax.swing.JLabel();
        jLabelEvenement = new javax.swing.JLabel();
        jLabelParticipants = new javax.swing.JLabel();
        jButtonAjouter = new javax.swing.JButton();
        jComboBoxEvenement = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListParticipant = new javax.swing.JList<>();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelAjouterInvite.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabelAjouterInvite.setText("Ajouter des invités");

        jLabelEvenement.setText("Evévnement");

        jLabelParticipants.setText("Participants");

        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        jComboBoxEvenement.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEvenement.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEvenementItemStateChanged(evt);
            }
        });

        jListParticipant.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListParticipant);

        jMenu5.setText("Nouveau");

        jMenuItem6.setText("Ajouter un événement");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem2.setText("Ajouter un participant");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem3.setText("Ajouter des invités");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuBar3.add(jMenu5);

        jMenu2.setText("Voir");

        jMenuItem4.setText("Consulter les événements");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar3.add(jMenu2);

        jMenu3.setText("Action");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem7.setText("Revenir à l'accueil");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Se déconnecter");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar3.add(jMenu3);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelEvenement, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxEvenement, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelParticipants, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAjouter)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelAjouterInvite))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAjouterInvite)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEvenement, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEvenement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelParticipants, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButtonAjouter)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        
        JOptionPane d = new JOptionPane();
        
        if ( this.checkForm() ) {
            
            for ( Participant participant : this.getJListParticipant() ) {
                
                Invitation invitation = new Invitation();
                invitation.setEvenement( this.getJComboBoxEvenement() );
                invitation.setParticipant( participant );
                
                new InvitationDAO().create( invitation );
            }

            d.showMessageDialog(this, "Votre invitation a bien été ajouté !", "Message", JOptionPane.INFORMATION_MESSAGE);
            
            this.setVisible( false );

            new AccueilWD().setVisible( true );
        
        } else {
            
            d.showMessageDialog(this, "Veuillez vérifier les informations", "Message", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jComboBoxEvenementItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEvenementItemStateChanged
        
        if ( evt.getStateChange() == ItemEvent.SELECTED ) {
        
            this.participants = new ParticipantDAO().findAllNotByEvenement( this.getJComboBoxEvenement().getId() );
            
            DefaultListModel listModel = new DefaultListModel();
        
            for ( Participant participant : this.participants )
                listModel.addElement( participant.getNom() + participant.getPrenom() + " - " + participant.getEmail() );

            this.jListParticipant.setSelectionMode( ListSelectionModel.MULTIPLE_INTERVAL_SELECTION );
            this.jListParticipant.setLayoutOrientation( JList.VERTICAL );
            this.jListParticipant.setVisibleRowCount( -1 );
            this.jListParticipant.setModel( listModel );
        }
    }//GEN-LAST:event_jComboBoxEvenementItemStateChanged

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

        this.setVisible( false );

        new EvenementWD().setVisible( true );
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        this.setVisible( false );

        new ParticipantWD().setVisible( true );
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        this.setVisible( false );

        new InvitationWD().setVisible( true );
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        this.setVisible( false );

        new ViewEvenementWD().setVisible( true );
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed

        this.setVisible( false );

        new AccueilWD().setVisible( true );
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed

        this.setVisible( false );

        new AuthentificationWD().setVisible( true );
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed

    }//GEN-LAST:event_jMenu3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvitationWD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvitationWD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvitationWD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvitationWD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvitationWD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JComboBox<String> jComboBoxEvenement;
    private javax.swing.JLabel jLabelAjouterInvite;
    private javax.swing.JLabel jLabelEvenement;
    private javax.swing.JLabel jLabelParticipants;
    private javax.swing.JList<String> jListParticipant;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
